; QuietMic installer translations. Keep this file UTF-8 with BOM for NSIS Unicode builds.
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "Korean"
!insertmacro MUI_LANGUAGE "Japanese"
!insertmacro MUI_LANGUAGE "SimpChinese"
!insertmacro MUI_LANGUAGE "TradChinese"
!insertmacro MUI_LANGUAGE "Spanish"
!insertmacro MUI_LANGUAGE "French"
!insertmacro MUI_LANGUAGE "German"

LangString MainSection ${LANG_ENGLISH} "QuietMic"
LangString InstallerBusy ${LANG_ENGLISH} "A QuietMic installation or removal is already in progress."
LangString RequiresX64 ${LANG_ENGLISH} "QuietMic requires 64-bit Windows 11."
LangString RequiresWin11 ${LANG_ENGLISH} "QuietMic requires Windows 11 or later."
LangString DriverVerificationFailed ${LANG_ENGLISH} "Driver signature verification failed. The app and device were not installed."
LangString CloseApp ${LANG_ENGLISH} "Exit QuietMic from the tray menu, then run the installer again."
LangString CopyFailed ${LANG_ENGLISH} "Could not copy the app files. Run the installer again."
LangString SetupFailed ${LANG_ENGLISH} "Virtual microphone setup failed with error $Result. Run the installer again or remove QuietMic from Windows Apps."
LangString HelperFailed ${LANG_ENGLISH} "The setup helper could not run or prepare its files. Check Windows Security and the installation log."
LangString UninstallCleanupFailed ${LANG_ENGLISH} "Could not clean up the QuietMic connection. Exit the app and try again. App files were preserved."
LangString UninstallHelperFailed ${LANG_ENGLISH} "The removal helper could not run. App files and the uninstall entry were preserved."

LangString MainSection ${LANG_KOREAN} "QuietMic"
LangString InstallerBusy ${LANG_KOREAN} "QuietMic 설치 또는 제거가 이미 진행 중입니다."
LangString RequiresX64 ${LANG_KOREAN} "QuietMic은 64비트 Windows 11이 필요합니다."
LangString RequiresWin11 ${LANG_KOREAN} "QuietMic은 Windows 11 이상이 필요합니다."
LangString DriverVerificationFailed ${LANG_KOREAN} "드라이버 서명 검증에 실패했습니다. 앱과 장치를 설치하지 않았습니다."
LangString CloseApp ${LANG_KOREAN} "QuietMic을 트레이 메뉴에서 종료한 후 설치기를 다시 실행하세요."
LangString CopyFailed ${LANG_KOREAN} "앱 파일을 복사하지 못했습니다. 설치기를 다시 실행하세요."
LangString SetupFailed ${LANG_KOREAN} "가상 마이크 설정에 실패했습니다. 오류 코드: $Result. 설치기를 다시 실행하거나 Windows 앱에서 QuietMic을 제거하세요."
LangString HelperFailed ${LANG_KOREAN} "설치 도우미를 실행하거나 파일을 준비하지 못했습니다. Windows 보안과 설치 로그를 확인하세요."
LangString UninstallCleanupFailed ${LANG_KOREAN} "QuietMic 연결을 정리하지 못했습니다. 앱을 종료하고 다시 시도하세요. 앱 파일은 보존했습니다."
LangString UninstallHelperFailed ${LANG_KOREAN} "제거 도우미를 실행하지 못했습니다. 앱 파일과 제거 항목은 보존했습니다."

LangString MainSection ${LANG_JAPANESE} "QuietMic"
LangString InstallerBusy ${LANG_JAPANESE} "QuietMic のインストールまたは削除がすでに進行中です。"
LangString RequiresX64 ${LANG_JAPANESE} "QuietMic には 64 ビット版 Windows 11 が必要です。"
LangString RequiresWin11 ${LANG_JAPANESE} "QuietMic には Windows 11 以降が必要です。"
LangString DriverVerificationFailed ${LANG_JAPANESE} "ドライバー署名の検証に失敗しました。アプリとデバイスはインストールされませんでした。"
LangString CloseApp ${LANG_JAPANESE} "トレイメニューから QuietMic を終了し、インストーラーをもう一度実行してください。"
LangString CopyFailed ${LANG_JAPANESE} "アプリのファイルをコピーできませんでした。インストーラーをもう一度実行してください。"
LangString SetupFailed ${LANG_JAPANESE} "仮想マイクの設定に失敗しました。エラー: $Result。インストーラーを再実行するか、Windows のアプリから QuietMic を削除してください。"
LangString HelperFailed ${LANG_JAPANESE} "セットアップヘルパーを実行できないか、ファイルを準備できませんでした。Windows セキュリティとインストールログを確認してください。"
LangString UninstallCleanupFailed ${LANG_JAPANESE} "QuietMic 接続を削除できませんでした。アプリを終了して再試行してください。アプリのファイルは保持されました。"
LangString UninstallHelperFailed ${LANG_JAPANESE} "削除ヘルパーを実行できませんでした。アプリのファイルとアンインストール項目は保持されました。"

LangString MainSection ${LANG_SIMPCHINESE} "QuietMic"
LangString InstallerBusy ${LANG_SIMPCHINESE} "QuietMic 安装或卸载已在进行中。"
LangString RequiresX64 ${LANG_SIMPCHINESE} "QuietMic 需要 64 位 Windows 11。"
LangString RequiresWin11 ${LANG_SIMPCHINESE} "QuietMic 需要 Windows 11 或更高版本。"
LangString DriverVerificationFailed ${LANG_SIMPCHINESE} "驱动程序签名验证失败。未安装应用和设备。"
LangString CloseApp ${LANG_SIMPCHINESE} "请从托盘菜单退出 QuietMic，然后重新运行安装程序。"
LangString CopyFailed ${LANG_SIMPCHINESE} "无法复制应用文件。请重新运行安装程序。"
LangString SetupFailed ${LANG_SIMPCHINESE} "虚拟麦克风设置失败，错误代码：$Result。请重新运行安装程序，或从 Windows 应用中卸载 QuietMic。"
LangString HelperFailed ${LANG_SIMPCHINESE} "无法运行安装助手或准备其文件。请检查 Windows 安全中心和安装日志。"
LangString UninstallCleanupFailed ${LANG_SIMPCHINESE} "无法清理 QuietMic 连接。请退出应用后重试。应用文件已保留。"
LangString UninstallHelperFailed ${LANG_SIMPCHINESE} "无法运行卸载助手。应用文件和卸载项已保留。"

LangString MainSection ${LANG_TRADCHINESE} "QuietMic"
LangString InstallerBusy ${LANG_TRADCHINESE} "QuietMic 安裝或移除已在進行中。"
LangString RequiresX64 ${LANG_TRADCHINESE} "QuietMic 需要 64 位元 Windows 11。"
LangString RequiresWin11 ${LANG_TRADCHINESE} "QuietMic 需要 Windows 11 或更新版本。"
LangString DriverVerificationFailed ${LANG_TRADCHINESE} "驅動程式簽章驗證失敗。未安裝應用程式與裝置。"
LangString CloseApp ${LANG_TRADCHINESE} "請從系統匣選單結束 QuietMic，然後重新執行安裝程式。"
LangString CopyFailed ${LANG_TRADCHINESE} "無法複製應用程式檔案。請重新執行安裝程式。"
LangString SetupFailed ${LANG_TRADCHINESE} "虛擬麥克風設定失敗，錯誤代碼：$Result。請重新執行安裝程式，或從 Windows 應用程式移除 QuietMic。"
LangString HelperFailed ${LANG_TRADCHINESE} "無法執行安裝小幫手或準備檔案。請檢查 Windows 安全性與安裝記錄。"
LangString UninstallCleanupFailed ${LANG_TRADCHINESE} "無法清理 QuietMic 連線。請結束應用程式後再試一次。應用程式檔案已保留。"
LangString UninstallHelperFailed ${LANG_TRADCHINESE} "無法執行移除小幫手。應用程式檔案與解除安裝項目已保留。"

LangString MainSection ${LANG_SPANISH} "QuietMic"
LangString InstallerBusy ${LANG_SPANISH} "Ya hay una instalación o desinstalación de QuietMic en curso."
LangString RequiresX64 ${LANG_SPANISH} "QuietMic requiere Windows 11 de 64 bits."
LangString RequiresWin11 ${LANG_SPANISH} "QuietMic requiere Windows 11 o posterior."
LangString DriverVerificationFailed ${LANG_SPANISH} "No se pudo verificar la firma del controlador. La aplicación y el dispositivo no se instalaron."
LangString CloseApp ${LANG_SPANISH} "Cierre QuietMic desde el menú de la bandeja y vuelva a ejecutar el instalador."
LangString CopyFailed ${LANG_SPANISH} "No se pudieron copiar los archivos de la aplicación. Vuelva a ejecutar el instalador."
LangString SetupFailed ${LANG_SPANISH} "Falló la configuración del micrófono virtual con el error $Result. Vuelva a ejecutar el instalador o quite QuietMic desde Aplicaciones de Windows."
LangString HelperFailed ${LANG_SPANISH} "No se pudo ejecutar el asistente de instalación ni preparar sus archivos. Revise Seguridad de Windows y el registro de instalación."
LangString UninstallCleanupFailed ${LANG_SPANISH} "No se pudo limpiar la conexión de QuietMic. Cierre la aplicación e inténtelo de nuevo. Los archivos se conservaron."
LangString UninstallHelperFailed ${LANG_SPANISH} "No se pudo ejecutar el asistente de desinstalación. Se conservaron los archivos y la entrada de desinstalación."

LangString MainSection ${LANG_FRENCH} "QuietMic"
LangString InstallerBusy ${LANG_FRENCH} "Une installation ou suppression de QuietMic est déjà en cours."
LangString RequiresX64 ${LANG_FRENCH} "QuietMic nécessite Windows 11 64 bits."
LangString RequiresWin11 ${LANG_FRENCH} "QuietMic nécessite Windows 11 ou une version ultérieure."
LangString DriverVerificationFailed ${LANG_FRENCH} "La vérification de la signature du pilote a échoué. L’application et le périphérique n’ont pas été installés."
LangString CloseApp ${LANG_FRENCH} "Quittez QuietMic depuis le menu de la zone de notification, puis relancez le programme d’installation."
LangString CopyFailed ${LANG_FRENCH} "Impossible de copier les fichiers de l’application. Relancez le programme d’installation."
LangString SetupFailed ${LANG_FRENCH} "La configuration du microphone virtuel a échoué avec l’erreur $Result. Relancez le programme d’installation ou supprimez QuietMic depuis les applications Windows."
LangString HelperFailed ${LANG_FRENCH} "Impossible d’exécuter l’assistant d’installation ou de préparer ses fichiers. Vérifiez Sécurité Windows et le journal d’installation."
LangString UninstallCleanupFailed ${LANG_FRENCH} "Impossible de nettoyer la connexion QuietMic. Quittez l’application et réessayez. Les fichiers ont été conservés."
LangString UninstallHelperFailed ${LANG_FRENCH} "Impossible d’exécuter l’assistant de suppression. Les fichiers et l’entrée de désinstallation ont été conservés."

LangString MainSection ${LANG_GERMAN} "QuietMic"
LangString InstallerBusy ${LANG_GERMAN} "Eine Installation oder Deinstallation von QuietMic wird bereits ausgeführt."
LangString RequiresX64 ${LANG_GERMAN} "QuietMic benötigt 64-Bit-Windows 11."
LangString RequiresWin11 ${LANG_GERMAN} "QuietMic benötigt Windows 11 oder höher."
LangString DriverVerificationFailed ${LANG_GERMAN} "Die Treibersignatur konnte nicht überprüft werden. App und Gerät wurden nicht installiert."
LangString CloseApp ${LANG_GERMAN} "Beenden Sie QuietMic über das Infobereichsmenü und starten Sie das Installationsprogramm erneut."
LangString CopyFailed ${LANG_GERMAN} "Die App-Dateien konnten nicht kopiert werden. Starten Sie das Installationsprogramm erneut."
LangString SetupFailed ${LANG_GERMAN} "Die Einrichtung des virtuellen Mikrofons ist mit Fehler $Result fehlgeschlagen. Starten Sie das Installationsprogramm erneut oder entfernen Sie QuietMic über Windows-Apps."
LangString HelperFailed ${LANG_GERMAN} "Der Einrichtungshelfer konnte nicht ausgeführt oder seine Dateien konnten nicht vorbereitet werden. Prüfen Sie Windows-Sicherheit und das Installationsprotokoll."
LangString UninstallCleanupFailed ${LANG_GERMAN} "Die QuietMic-Verbindung konnte nicht bereinigt werden. Beenden Sie die App und versuchen Sie es erneut. Die App-Dateien wurden beibehalten."
LangString UninstallHelperFailed ${LANG_GERMAN} "Der Deinstallationshelfer konnte nicht ausgeführt werden. App-Dateien und Deinstallationseintrag wurden beibehalten."
